#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xwallpaper --center /home/kafeks/Pictures/wallpapers/Dark_Nature.png

bspc rule -a microsoft-edge-stable private=on dekstop=1
bspc rule -a kitty private=on dekstop= 4
bspc rule -a vesktop private=on dekstop=2
bspc rule -a thunar private=on dekstop=5
bspc rule -a telegram-desktop private=on dekstop=3
bspc rule -a code private=on dekstop=6


#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf
nitrogen --restore &
dunst &
polybar &
nvidiasettings &
